---
- name: "Include vars"
  ansible.builtin.include_vars: "../vars/{{ env }}/ah_ee_namespaces.yml"
  tags:
    - "ee_namespaces"

- name: "Import ah_configuration role"
  ansible.builtin.import_role:
    name: "redhat_cop.ah_configuration.ee_namespace"
  tags:
    - "ee_namespaces"
...
