---
- name: "Include vars"
  ansible.builtin.include_vars: "../vars/{{ env }}/ah_ee_repositories.yml"
  tags:
    - "ee_repos"

- name: "Import ah_configuration role"
  ansible.builtin.import_role:
    name: "redhat_cop.ah_configuration.ee_repository"
  tags:
    - "ee_repos"
...
