---
- name: "Include vars"
  ansible.builtin.include_vars: "../vars/{{ env }}/ah_groups.yml"
  tags:
    - "groups"

- name: "Import ah_configuration role"
  ansible.builtin.import_role:
    name: "redhat_cop.ah_configuration.group"
  tags:
    - "groups"
...
