---
- name: "Include vars"
  ansible.builtin.include_vars: "../vars/{{ env }}/ah_ee_registry_sync.yml"
  tags:
    - "regsync"

- name: "Import ah_configuration role"
  ansible.builtin.import_role:
    name: "redhat_cop.ah_configuration.ee_registry_sync"
  tags:
    - "regsync"
...
