---
- name: "Include vars"
  ansible.builtin.include_vars: "../vars/{{ env }}/ah_users.yml"
  tags:
    - "users"

- name: "Import ah_configuration role"
  ansible.builtin.import_role:
    name: "redhat_cop.ah_configuration.user"
  tags:
    - "users"
...
