---
- name: "Include vars"
  ansible.builtin.include_vars: "../vars/{{ env }}/ah_collection_publish.yml"
  tags:
    - "publish"

- name: "Import ah_configuration role"
  ansible.builtin.import_role:
    name: "redhat_cop.ah_configuration.publish"
  tags:
    - "publish"
...
