---
- name: "Include vars"
  ansible.builtin.include_vars: "../vars/{{ env }}/ah_collection_namespaces.yml"
  tags:
    - "namespaces"

- name: "Import ah_configuration role"
  ansible.builtin.import_role:
    name: "redhat_cop.ah_configuration.namespace"
  tags:
    - "namespaces"
...
